name: Publish to PyPI

on:
  push:
    tags:
      - v*.*.*

jobs:

  wheel-linux-aarch64:
    name: Build Linux wheels (Aarch64)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64
    - name: Build manylinux wheels
      uses: pypa/cibuildwheel@v2.22.0
      env:
        CIBW_ARCHS: aarch64
        CIBW_BUILD: '*-manylinux_aarch64'
        CIBW_BUILD_VERBOSITY: 2
      with:
        output-dir: dist
    - uses: actions/upload-artifact@v4
      with:
        name: wheels-manylinux_aarch64
        path: dist/*

  wheel-linux-x86_64:
    name: Build Linux wheels (x86-64)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build manylinux wheels
      uses: pypa/cibuildwheel@v2.22.0
      env:
        CIBW_ARCHS: x86_64
        CIBW_BUILD: '*-manylinux_x86_64'
        CIBW_BUILD_VERBOSITY: 2
      with:
        output-dir: dist
    - uses: actions/upload-artifact@v4
      with:
        name: wheels-manylinux_x86_64
        path: dist/*

  wheel-macos-x86_64:
    name: Build MacOS wheels (x86-64)
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Build manylinux wheels
      uses: pypa/cibuildwheel@v2.22.0
      env:
        CIBW_ARCHS: x86_64
        CIBW_BUILD: '*-macosx_x86_64'
        CIBW_BUILD_VERBOSITY: 2
      with:
        output-dir: dist
    - uses: actions/upload-artifact@v4
      with:
        name: wheels-macosx_x86_64
        path: dist/*

  wheel-macos-aarch64:
    name: Build MacOS wheels (Aarch64)
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Build manylinux wheels
      uses: pypa/cibuildwheel@v2.22.0
      env:
        CIBW_ARCHS: arm64
        CIBW_BUILD: '*-macosx_arm64'
        CIBW_BUILD_VERBOSITY: 2
      with:
        output-dir: dist
    - uses: actions/upload-artifact@v4
      with:
        name: wheels-macosx_arm64
        path: dist/*

  wheel-win32-x86_64:
    name: Build Windows wheels (x86-64)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Configure build for amd64
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64
    - name: Build manylinux wheels
      uses: pypa/cibuildwheel@v2.22.0
      env:
        CIBW_ARCHS: AMD64
        CIBW_BUILD: '*-win_amd64'
        CIBW_BUILD_VERBOSITY: 2
      with:
        output-dir: dist
    - uses: actions/upload-artifact@v4
      with:
        name: wheels-win_amd64
        path: dist/*

  sdist:
    runs-on: ubuntu-latest
    name: Build source distribution
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install build requirements
      run: python -m pip install -r .github/workflows/requirements.txt
    - name: Build source distribution
      run: python -m build -s .
    - name: Store built source distribution
      uses: actions/upload-artifact@v4
      with:
        name: sdist
        path: dist/*

  test-sdist:
    runs-on: ubuntu-latest
    name: Test source distribution
    needs:
    - sdist
    steps:
    - uses: dtolnay/rust-toolchain@stable
    - name: Setup Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Download built wheels
      uses: actions/download-artifact@v4
      with:
          name: sdist
          path: dist/
    - name: Update pip to latest version
      run: python -m pip install -U pip
    - name: Install built wheel
      run: python -m pip install --no-binary sphinxcontrib-svgbob --find-links=dist sphinxcontrib-svgbob
    - name: Run built-in tests
      run: python -m unittest sphinxcontrib.svgbob.tests -vv

  upload:
    environment: PyPI
    runs-on: ubuntu-latest
    name: Upload
    permissions:
      id-token: write
    needs:
    - sdist
    - test-sdist
    - wheel-linux-aarch64
    - wheel-linux-x86_64
    - wheel-macos-aarch64
    - wheel-macos-x86_64
    - wheel-win32-x86_64
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: sdist
        path: dist
        merge-multiple: true
    - uses: actions/download-artifact@v4
      with:
        pattern: wheels-*
        path: dist
        merge-multiple: true
    - name: Publish distributions to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1

  release:
    environment: GitHub Releases
    runs-on: ubuntu-latest
    permissions: write-all
    if: "!contains(github.ref, 'rc')"
    name: Release
    needs: upload
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Release a Changelog
      uses: rasmus-saks/release-a-changelog-action@v1.2.0
      with:
        github-token: '${{ secrets.GITHUB_TOKEN }}'

